openapi: "3.0.3"
info:
  title: "ZIPs REST API"
  description: "My first API"
  version: "v1.0"

# this is a comment
servers:
  - url: http://localhost:3000
    description: "Development server"

components:
  schemas:
    states:
      type: string
      description: State Id
      enum: [ "MA", "RI", "NH", "ME", "VT", "CT", "NY", "NJ", "PA", 
              "DE", "DC", "MD", "VA", "WV", "NC", "SC", "GA", "FL", 
              "AL", "TN", "MS", "KY", "OH", "IN", "MI", "IA", "WI", 
              "MN", "SD", "ND", "MT", "IL", "MO", "KS", "NE", "LA", 
              "AR", "OK", "TX", "CO", "WY", "ID", "UT", "AZ", "NM", 
              "NV", "CA", "HI", "OR", "WA", "AK" ]

    city:
      type: object
      required: [ "city","pop","loc","state" ]
      properties:
        _Id:
          type: string
          description: Id
        city:
          type: string
          description: City name
        pop:
          type: number
          description: city population
        loc:
          type: array
          items:
            type: number
          minItems: 2
          maxItems: 2
        state:
          type: string
          description: State Id
          enum: [ "MA", "RI", "NH", "ME", "VT", "CT", "NY", "NJ", "PA", 
                  "DE", "DC", "MD", "VA", "WV", "NC", "SC", "GA", "FL", 
                  "AL", "TN", "MS", "KY", "OH", "IN", "MI", "IA", "WI", 
                  "MN", "SD", "ND", "MT", "IL", "MO", "KS", "NE", "LA", 
                  "AR", "OK", "TX", "CO", "WY", "ID", "UT", "AZ", "NM", 
                  "NV", "CA", "HI", "OR", "WA", "AK" ] 

    city-form:
      type: object
      required: [ "city","pop","lat",lng","state" ]
      properties:
        city:
          type: string
          description: City name
        pop:
          type: number
          description: city population
        lat:
          type: number
          description: City's latitude
        lng:
          type: number
          description: City's longitude
        state:
          type: string
          description: State Id
          enum: [ "MA", "RI", "NH", "ME", "VT", "CT", "NY", "NJ", "PA", 
                  "DE", "DC", "MD", "VA", "WV", "NC", "SC", "GA", "FL", 
                  "AL", "TN", "MS", "KY", "OH", "IN", "MI", "IA", "WI", 
                  "MN", "SD", "ND", "MT", "IL", "MO", "KS", "NE", "LA", 
                  "AR", "OK", "TX", "CO", "WY", "ID", "UT", "AZ", "NM", 
                  "NV", "CA", "HI", "OR", "WA", "AK" ] 
      
paths:
  /api/city:
    post:
      summary:  add anew city
      operationId: addcity
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/city-form"
          application/json:
            schema:
                $ref: "#/components/schemas/city"
      responses:
        201:
          description: success
          content:
              application/json:
                  schema:
                    type: object
                    properties:
                        message:
                            type: string
                  

  /api/state/{stateId}:
    get:
      description: Get cities in a state
      operationId: getCitiesFromState
      parameters:
      - name: stateId
        in: path 
        required: true
        schema:
          $ref: "#/components/schemas/states"
      - name: offset
        in: query 
        schema:
          type: number
          minimum: 0
      - name: limit
        in: query 
        schema:
          type: number
          minimum: 1
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/city"

  /api/states:
      get:
        description: Get a list of all the states
        operationId: getStates
        responses:
            200:
                description: Default result representation
                content:
                    application/json:
                      schema:
                        type: array
                        items:
                          type: string 